### PR TITLE
fix: use named imports for express types

### LINKED ISSUE #281: index.d.ts: import Express from 'express'; error
### Description

After upgrading from v5 to v6, during TS compilation I've this error coming from index.d.ts of express-rate-limit (that seems autogenerated):

```
node_modules/express-rate-limit/dist/index.d.ts:3:8 - error TS1259: Module '"/home/dave/Job/myproject/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag

3 import Express from 'express';
         ~~~~~~~

  node_modules/@types/express/index.d.ts:133:1
    133 export = e;
        ~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

First lines of index.d.ts:
```
// Generated by dts-bundle-generator v6.2.0

import Express from 'express';
```

### Library version

6.0.4

### Node version

16.13.1

### Typescript version (if you are using it)

4.3.5

### Module system

CommonJS

### PR DESCRIPTION
**Pull request by gamemaker1**
## Related Issues

- Fixes #281

### Changed

- Use named imports for Express types.

### Removed

- Remove additional options from `tsconfig.json`s in the import tests.

## Caveats/Problems

- Still had to keep the `esModuleInterop` flag in the tests as the `express` import doesn't work otherwise.

## Checklist

- [x] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [x] All tests (`npm test`) pass.
- [x] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [x] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

File: test/external/imports/ts-cjs/tsconfig.json [hunk 1]
```diff
@@ -4,12 +4,11 @@
 	"compilerOptions": {
 		"target": "esnext",
 		"module": "commonjs",
-		"declaration": true,
+		"declaration": false,
```
Comment (nfriedly) [inline test/external/imports/ts-cjs/tsconfig.json:7]: `false` is the default, right? so, we can probably just omit this line now.

File: test/external/imports/ts-cjs/tsconfig.json [hunk 2]
```diff
@@ -4,12 +4,11 @@
...
 		"sourceMap": false,
-		"outDir": "build/",
 		"strict": true,
-		"moduleResolution": "node",
 		"esModuleInterop": true,
```
Comment (nfriedly) [inline test/external/imports/ts-cjs/tsconfig.json:10]: what happens if we turn off `esModuleInterop`?

File: test/external/imports/ts-cjs/tsconfig.json [hunk 3]
```diff
@@ -4,12 +4,11 @@
...
-		"skipLibCheck": true
+		"moduleResolution": "node",
```
Comment (nfriedly) [inline test/external/imports/ts-cjs/tsconfig.json:11]: this is the default also, right?

**Review by nfriedly — APPROVED** [review]
It seems like there's a few different things going on here, but if this fixes #281 then I think it's good.

File: package.json [hunk 4]
```diff
@@ -73,19 +73,19 @@
 		"express": "^4"
 	},
 	"devDependencies": {
-		"@jest/globals": "^27.4.2",
+		"@jest/globals": "^27.4.6",
 		"@types/express": "^4.17.13",
-		"@types/jest": "^27.0.3",
-		"@types/node": "^16.11.17",
+		"@types/jest": "^27.4.0",
+		"@types/node": "^17.0.8",
```
Comment (DavideViolante) [inline package.json:79]: I would not use a non LTS node version here

File: test/external/imports/ts-cjs/tsconfig.json [hunk 5]
```diff
@@ -4,12 +4,11 @@
 	"compilerOptions": {
 		"target": "esnext",
 		"module": "commonjs",
-		"declaration": true,
+		"declaration": false,
 		"sourceMap": false,
```
Comment (DavideViolante) [inline test/external/imports/ts-cjs/tsconfig.json:8]: Default is [false](https://www.typescriptlang.org/tsconfig#sourceMap), this line can be deleted

File: test/external/imports/ts-cjs/tsconfig.json [hunk 6]
```diff
@@ -4,12 +4,11 @@
...
-		"outDir": "build/",
```
Comment (DavideViolante) [inline test/external/imports/ts-cjs/tsconfig.json:9]: Idk if this is correct, generated files now won't go inside this dir.

File: test/external/imports/ts-esm/tsconfig.json [hunk 7]
```diff
@@ -4,12 +4,11 @@
 	"compilerOptions": {
 		"target": "esnext",
 		"module": "esnext",
-		"declaration": true,
+		"declaration": false,
 		"sourceMap": false,
```
Comment (DavideViolante) [inline test/external/imports/ts-esm/tsconfig.json:8]: As above, this is false by default, can be removed.

File: test/external/stores/tsconfig.json [hunk 8]
```diff
@@ -4,12 +4,10 @@
 	"compilerOptions": {
 		"target": "esnext",
 		"module": "esnext",
-		"declaration": true,
+		"declaration": false,
 		"sourceMap": false,
```
Comment (DavideViolante) [inline test/external/stores/tsconfig.json:8]: Same

File: test/external/imports/ts-cjs/tsconfig.json (hunk 3 above)
Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json:11]: `classic` is the default - https://www.typescriptlang.org/tsconfig#moduleResolution

File: package.json (hunk 4 above)
Comment (gamemaker1) [reply package.json:79]: Arghhh that's the second time that's happened - I bump all the deps and this gets bumped too 🤦🏾 Maybe I should pin that to 16.x instead, until the next LTS version.

File: test/external/imports/ts-cjs/tsconfig.json (hunk 5 above)
Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json:8]: Will do

File: test/external/imports/ts-cjs/tsconfig.json (hunk 2 above)
Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json:10]: We get the following when running the `ts-cjs` test:

```
    test/server-test.ts:4:8 - error TS1259: Module '"/data/code/contrib/express-rate-limit/core/test/external/imports/ts-cjs/node_modules/@types/supertest/index"' can only be default-imported using the 'esModuleInterop' flag

    4 import request from 'supertest'
             ~~~~~~~

      node_modules/@types/supertest/index.d.ts:10:1
        10 export = supertest;
           ~~~~~~~~~~~~~~~~~~~
        This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
    test/server-test.ts:4:8 - error TS1259: Module '"/data/code/contrib/express-rate-limit/core/test/external/imports/ts-cjs/node_modules/@types/supertest/index"' can only be default-imported using the 'esModuleInterop' flag

    4 import request from 'supertest'
             ~~~~~~~

      node_modules/@types/supertest/index.d.ts:10:1
        10 export = supertest;
           ~~~~~~~~~~~~~~~~~~~
        This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

We could use `const request = require('supertest')` instead in those files... that seems to fix the problem

**Comment by DavideViolante** [comment]
@gamemaker1 to fix `Unsafe call of an any typed value. ` linting errors replace supertest imports with:
`import { agent as request } from 'supertest'`
Then run `npm run lint` before committing to ensure there are no errors.

**Comment by gamemaker1** [comment]
> `import { agent as request } from 'supertest'`

Thanks, that worked!

File: test/external/imports/ts-cjs/tsconfig.json (hunk 2 above)
Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json]: Fixed - https://github.com/nfriedly/express-rate-limit/pull/282#issuecomment-1006397135 🎉

Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json]: Nope not fixed 😕

Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json]: We need this so that we can do 

```ts
import createServer from 'express'

const app = createServer()
```

A possible fix is to use `import createServer = require('express')`

Comment (gamemaker1) [reply test/external/imports/ts-cjs/tsconfig.json]: Even `import createServer = require('express')` doesn't work :/

File: tsconfig.json [hunk 9]
```diff
@@ -7,6 +7,7 @@
 		"noUnusedLocals": true,
 		"noImplicitReturns": true,
 		"noFallthroughCasesInSwitch": true,
+		"esModuleInterop": true,
```
Comment (DavideViolante) [inline tsconfig.json:10]: This can be safely deleted, everything else LGTM. :+1:

Comment (gamemaker1) [reply tsconfig.json:10]: Unfortunately it can't - https://github.com/nfriedly/express-rate-limit/pull/282#discussion_r779435279

**Review by DavideViolante — APPROVED** [review]

File: tsconfig.json (hunk 9 above)
Comment (gamemaker1) [reply tsconfig.json:10]: I think we can let this remain as now we don't need users to use the `esModuleInterop` flag, only the library needs to use it to make sure we can run the tests.

**Comment by gamemaker1** [comment]
@nfriedly if these changes look good, either of us could make a patch release?

File: test/external/imports/js-cjs/package.json [hunk 10]
```diff
@@ -9,7 +9,7 @@
 	},
 	"dependencies": {
 		"express": "^4.17.2",
-		"express-rate-limit": "file:../../../../express-rate-limit-6.0.3.tgz"
+		"express-rate-limit": "file:../../../../express-rate-limit-6.0.4.tgz"
```
Comment (nfriedly) [inline test/external/imports/js-cjs/package.json:12]: Is this going to work once I bump it to 6.0.5 for this next release?

Comment (nfriedly) [reply test/external/imports/js-cjs/package.json:12]: Looking through the history, it looks like no, although I'm not sure I understand why...

**Review by nfriedly — APPROVED** [review]
@gamemaker1 

> if these changes look good, either of us could make a patch release?

Yea, I had one question about the .tgz dependency, but it doesn't look like it blocks the release, so lets ship this as 6.0.5. Would you like to do the honors?

File: test/external/imports/js-cjs/package.json (hunk 10 above)
Comment (gamemaker1) [reply test/external/imports/js-cjs/package.json:12]: Hmmm this has started to bug me too :/

> Looking through the history, it looks like no, although I'm not sure I understand why...

It runs `npm install ../../../express-rate-limit-*.tgz` every time the test runs on CI/locally, so the version number is bumped - but not committed to git. When we run it locally though, the version number is bumped and if we do a `git add .`, it commits that change too.

I think we can link the package to the folder instead of a .tgz - that should remove this version bump thingie.

**Comment by gamemaker1** [comment]
> Would you like to do the honors?

Yes, hooray!

File: test/external/imports/js-cjs/package.json (hunk 10 above)
Comment (gamemaker1) [reply test/external/imports/js-cjs/package.json:12]: Releasing 6.0.5 first, then will try out this fix

**Comment by gamemaker1** [comment]
Yay 6.0.5 is live!

File: test/external/imports/js-cjs/package.json (hunk 10 above)
Comment (DavideViolante) [reply test/external/imports/js-cjs/package.json:12]: Why can't we just specify the version and use the package from npm here? Just to know.

Comment (gamemaker1) [reply test/external/imports/js-cjs/package.json:12]: Because we want to run the tests with the changes made on a branch on the repo before publishing to npm - there's no point in testing after publishing the module 😅

Comment (gamemaker1) [reply test/external/imports/js-cjs/package.json:12]: Opened #283 for this

Comment (DavideViolante) [reply test/external/imports/js-cjs/package.json:12]: I think we can create a GitHub Action that runs the test on that branch (any new branch), and if tests dont pass, publish wont happen.

Comment (gamemaker1) [reply test/external/imports/js-cjs/package.json:12]: That is how it works currently - https://github.com/nfriedly/express-rate-limit/blob/master/.github/workflows/ci.yaml
