### ISSUE TITLE
TypeError: (0 , express_rate_limit_1.default) is not a function

### ISSUE THREAD

**Issue by 56789a1987** [nfriedly/express-rate-limit#275]
### Description

This error appears after updating from 6.0.1 to 6.0.3
I'm using it in TypeScript. The output is CommonJS.

The following import does not work as expected:
`import rateLimit from 'express-rate-limit';`

There is no compile error, but I got this runtime error:
`TypeError: (0 , express_rate_limit_1.default) is not a function`

This import can make it work:
`import * as rateLimit from 'express-rate-limit';`
But TypeScript compiler does not recognize it. I need to call it in this way: `(rateLimit as any)({ ... })`

### Library version

6.0.3

### Node version

16.13.1

### Typescript version (if you are using it)

4.5.4

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @56789a1987,

I can't seem to replicate your issue, and the [import test for Typescript-CommonJS is passing](https://github.com/nfriedly/express-rate-limit/runs/4668606708?check_suite_focus=true). Could you please share some more info:

- Do you have `type: module` in your package.json?
- Could you please share your `tsconfig.json`?
- Could you paste the contents of what is in `node_modules/express-rate-limit/dist/index.cjs`?

Thanks

**Comment by 56789a1987** [comment]
@gamemaker1

- No `type: module` in module.json
- The `tsconfig.json`:
```json
{
	"compilerOptions": {
		"target": "es2020",
		"module": "CommonJS",
		"moduleResolution": "node",
		"importHelpers": true,
		"noEmitOnError": false,
		"declaration": false,
		"strict": true,
		"strictFunctionTypes": true,
		"sourceMap": true,
		"skipLibCheck": true,
	},
	"exclude": ["node_modules"]
}
```

**Comment by gamemaker1** [comment]
If I replace the tsconfig.json in the `ts-cjs` import test with yours, I get the following error:

```sh
source/app.ts:4:8 - error TS1259: Module '"node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag
```

Could you please try adding the `esModuleInterop` flag to your tsconfig.json?

**Comment by 56789a1987** [comment]
If I add `"esModuleInterop": true` to tsconfig.json, lots of `import` from other existing codes are broken for my workspace. It's unlikely I can add it.

**Comment by gamemaker1** [comment]
> Lots of import from other existing codes are broken for my workspace. It's unlikely I can add it.

Ohk...

Could you please paste the contents of `node_modules/express-rate-limit/dist/index.cjs`?

**Comment by 56789a1987** [comment]
```js
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);

// source/index.ts
var source_exports = {};
__export(source_exports, {
  default: () => source_default
});

// source/memory-store.ts
var calculateNextResetTime = (windowMs) => {
  const resetTime = new Date();
  resetTime.setMilliseconds(resetTime.getMilliseconds() + windowMs);
  return resetTime;
};
var MemoryStore = class {
  init(options) {
    this.windowMs = options.windowMs;
    this.resetTime = calculateNextResetTime(this.windowMs);
    this.hits = {};
    const interval = setInterval(async () => {
      await this.resetAll();
    }, this.windowMs);
    if (interval.unref) {
      interval.unref();
    }
  }
  async increment(key) {
    const totalHits = (this.hits[key] ?? 0) + 1;
    this.hits[key] = totalHits;
    return {
      totalHits,
      resetTime: this.resetTime
    };
  }
  async decrement(key) {
    const current = this.hits[key];
    if (current) {
      this.hits[key] = current - 1;
    }
  }
  async resetKey(key) {
    delete this.hits[key];
  }
  async resetAll() {
    this.hits = {};
    this.resetTime = calculateNextResetTime(this.windowMs);
  }
};

// source/lib.ts
var isLegacyStore = (store) => typeof store.incr === "function" && typeof store.increment !== "function";
var promisifyStore = (passedStore) => {
  if (!isLegacyStore(passedStore)) {
    return passedStore;
  }
  const legacyStore = passedStore;
  class PromisifiedStore {
    async increment(key) {
      return new Promise((resolve, reject) => {
        legacyStore.incr(key, (error, totalHits, resetTime) => {
          if (error)
            reject(error);
          resolve({ totalHits, resetTime });
        });
      });
    }
    async decrement(key) {
      return Promise.resolve(legacyStore.decrement(key));
    }
    async resetKey(key) {
      return Promise.resolve(legacyStore.resetKey(key));
    }
    async resetAll() {
      if (typeof legacyStore.resetAll === "function")
        return Promise.resolve(legacyStore.resetAll());
    }
  }
  return new PromisifiedStore();
};
var parseOptions = (passedOptions) => {
  const options = {
    windowMs: 60 * 1e3,
    store: new MemoryStore(),
    max: 5,
    message: "Too many requests, please try again later.",
    statusCode: 429,
    legacyHeaders: passedOptions.headers ?? true,
    standardHeaders: passedOptions.draft_polli_ratelimit_headers ?? false,
    requestPropertyName: "rateLimit",
    skipFailedRequests: false,
    skipSuccessfulRequests: false,
    requestWasSuccessful: (_request, response) => response.statusCode < 400,
    skip: (_request, _response) => false,
    keyGenerator: (request, _response) => {
      if (!request.ip) {
        console.error("WARN | `express-rate-limit` | `request.ip` is undefined. You can avoid this by providing a custom `keyGenerator` function, but it may be indicative of a larger issue.");
      }
      return request.ip;
    },
    handler: (_request, response, _next, _optionsUsed) => {
      response.status(options.statusCode).send(options.message);
    },
    onLimitReached: (_request, _response, _optionsUsed) => {
    },
    ...passedOptions
  };
  if (typeof options.store.incr !== "function" && typeof options.store.increment !== "function" || typeof options.store.decrement !== "function" || typeof options.store.resetKey !== "function" || typeof options.store.resetAll !== "undefined" && typeof options.store.resetAll !== "function" || typeof options.store.init !== "undefined" && typeof options.store.init !== "function") {
    throw new TypeError("An invalid store was passed. Please ensure that the store is a class that implements the `Store` interface.");
  }
  options.store = promisifyStore(options.store);
  return options;
};
var handleAsyncErrors = (fn) => async (request, response, next) => {
  try {
    await Promise.resolve(fn(request, response, next)).catch(next);
  } catch (error) {
    next(error);
  }
};
var rateLimit = (passedOptions) => {
  const options = parseOptions(passedOptions ?? {});
  if (typeof options.store.init === "function")
    options.store.init(options);
  const middleware = handleAsyncErrors(async (request, response, next) => {
    const skip = await options.skip(request, response);
    if (skip) {
      next();
      return;
    }
    const augmentedRequest = request;
    const key = await options.keyGenerator(request, response);
    const { totalHits, resetTime } = await options.store.increment(key);
    const retrieveQuota = typeof options.max === "function" ? options.max(request, response) : options.max;
    const maxHits = await retrieveQuota;
    augmentedRequest[options.requestPropertyName] = {
      limit: maxHits,
      current: totalHits,
      remaining: Math.max(maxHits - totalHits, 0),
      resetTime
    };
    if (options.legacyHeaders && !response.headersSent) {
      response.setHeader("X-RateLimit-Limit", maxHits);
      response.setHeader("X-RateLimit-Remaining", augmentedRequest[options.requestPropertyName].remaining);
      if (resetTime instanceof Date) {
        response.setHeader("Date", new Date().toUTCString());
        response.setHeader("X-RateLimit-Reset", Math.ceil(resetTime.getTime() / 1e3));
      }
    }
    if (options.standardHeaders && !response.headersSent) {
      response.setHeader("RateLimit-Limit", maxHits);
      response.setHeader("RateLimit-Remaining", augmentedRequest[options.requestPropertyName].remaining);
      if (resetTime) {
        const deltaSeconds = Math.ceil((resetTime.getTime() - Date.now()) / 1e3);
        response.setHeader("RateLimit-Reset", Math.max(0, deltaSeconds));
      }
    }
    if (options.skipFailedRequests || options.skipSuccessfulRequests) {
      let decremented = false;
      const decrementKey = async () => {
        if (!decremented) {
          await options.store.decrement(key);
          decremented = true;
        }
      };
      if (options.skipFailedRequests) {
        response.on("finish", async () => {
          if (!options.requestWasSuccessful(request, response))
            await decrementKey();
        });
        response.on("close", async () => {
          if (!response.writableEnded)
            await decrementKey();
        });
        response.on("error", async () => {
          await decrementKey();
        });
      }
      if (options.skipSuccessfulRequests) {
        response.on("finish", async () => {
          if (options.requestWasSuccessful(request, response))
            await decrementKey();
        });
      }
    }
    if (maxHits && totalHits === maxHits + 1) {
      options.onLimitReached(request, response, options);
    }
    if (maxHits && totalHits > maxHits) {
      if ((options.legacyHeaders || options.standardHeaders) && !response.headersSent) {
        response.setHeader("Retry-After", Math.ceil(options.windowMs / 1e3));
      }
      options.handler(request, response, next, options);
      return;
    }
    next();
  });
  middleware.resetKey = options.store.resetKey.bind(options.store);
  return middleware;
};
var lib_default = rateLimit;

// source/index.ts
var source_default = lib_default;
module.exports = __toCommonJS(source_exports);
module.exports = rateLimit;
```

**Comment by gamemaker1** [comment]
Hmmm... that looks correct

**Comment by gamemaker1** [comment]
Could you please paste the output of the following:

```ts
import rateLimit from 'express-rate-limit'

console.log(rateLimit)
```

**Comment by gamemaker1** [comment]
Could you also try using the old CommonJS style import instead:

```ts
import rateLimit = require('express-rate-limit')
```

**Comment by 56789a1987** [comment]
> Could you please paste the output of the following:
> 
> ```ts
> import rateLimit from 'express-rate-limit'
> 
> console.log(rateLimit)
> ```

This outputs `undefined`

**Comment by gamemaker1** [comment]
Ok, could you please try this - https://github.com/nfriedly/express-rate-limit/issues/275#issuecomment-1003283786?

**Comment by 56789a1987** [comment]
> Could you also try using the old CommonJS style import instead:
> 
> ```ts
> import rateLimit = require('express-rate-limit')
> ```

`[Function: rateLimit]`

**Comment by gamemaker1** [comment]
Ok, that seems to work 🎉

**Comment by gamemaker1** [comment]
I'll add this to the readme, thanks for filing this issue!

**Comment by 56789a1987** [comment]
> `[Function: rateLimit]`

But the TypeScript compiler does not recognize it. I need to use it like this: `(rateLimit as any)({ ... })` to pass the compile.

**Comment by gamemaker1** [comment]
What error do you get from the Typescript compiler when you use this:

```ts
import rateLimit = require('express-rate-limit')

// ...

app.use(rateLimit({
	// ...		
}))
```

**Comment by 56789a1987** [comment]
```
error TS2349: This expression is not callable.
  Type 'typeof import("/home/***/***/node_modules/express-rate-limit/dist/index")' has no call signatures.

109  return rateLimit({
            ~~~~~~~~~
```

**Comment by gamemaker1** [comment]
Ok, here's what I've figured out so far:

- `const ... = require('...')` is to be used for importing commonjs modules.
- `import ... from '...'` is to be used for importing types.
- If you interchange the above two, you get the `Type 'typeof import(".../node_modules/express-rate-limit/dist/index")' has no call signatures` error.
- This is only needed if `esModuleInterop` cannot be set to `true`.

The example server I tested it against:

```ts
// /source/index.ts
// Run the server

import { Request, Response } from 'express'
import { Store, IncrementResponse } from 'express-rate-limit'

const createServer = require('express')
const rateLimit = require('express-rate-limit')

class TestStore implements Store {
	hits: Record<string, number> = {}

	async increment(key: string): Promise<IncrementResponse> {
		if (!this.hits[key]) this.hits[key] = 0
		this.hits[key] += 1

		return {
			totalHits: this.hits[key],
			resetTime: undefined,
		}
	}

	async decrement(key: string): Promise<void> {
		if (this.hits[key]) this.hits[key]--
	}

	async resetKey(key: string): Promise<void> {
		delete this.hits[key]
	}
}

const app = createServer()

app.use(rateLimit({ max: 2, store: new TestStore() }))

app.get('/', (request: Request, response: Response) => response.send('Hello!'))

app.listen(8080, () =>
	console.log('Make a GET request to http://localhost:8080!')
)
```

**Comment by gamemaker1** [comment]
So to fix this issue, you could use the following:

```ts
const rateLimit = require('express-rate-limit')

// ...
```

And if you need to extend the default store or something else that requires you to import types from the library, use the following:

```ts
import { Store, IncrementResponse, IncrementCallback } from 'express-rate-limit'

// ...
```

**Comment by gamemaker1** [comment]
Does this work for you?

**Comment by 56789a1987** [comment]
This works

**Comment by gamemaker1** [comment]
That's great! I will add these observations to the readme as well.
