### ISSUE TITLE
index.d.ts: import Express from 'express'; error

### ISSUE THREAD

**Issue by DavideViolante** [nfriedly/express-rate-limit#281]
### Description

After upgrading from v5 to v6, during TS compilation I've this error coming from index.d.ts of express-rate-limit (that seems autogenerated):

```
node_modules/express-rate-limit/dist/index.d.ts:3:8 - error TS1259: Module '"/home/dave/Job/myproject/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag

3 import Express from 'express';
         ~~~~~~~

  node_modules/@types/express/index.d.ts:133:1
    133 export = e;
        ~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

First lines of index.d.ts:
```
// Generated by dts-bundle-generator v6.2.0

import Express from 'express';
```

### Library version

6.0.4

### Node version

16.13.1

### Typescript version (if you are using it)

4.3.5

### Module system

CommonJS

**Comment by nfriedly** [comment]
Can you try turning on esModuleInterop in your typescript config?

See https://github.com/nfriedly/express-rate-limit#typescript

**Comment by nfriedly** [comment]
You can also take a look at our ts-cjs test for a working example of the library being used with TypeScript and CommonJS: https://github.com/nfriedly/express-rate-limit/tree/master/test/external/imports/ts-cjs

**Comment by DavideViolante** [comment]
My code is the same, even simpler, as the TS CJS example:

```ts
...
import expressRateLimit from 'express-rate-limit';
...
app.use('/api/', expressRateLimit({ max: 900, windowMs: 15 * 60 * 1000 }));
...
```

There are no errors raised here actually.
**The error is raised inside `node_modules/express-rate-limit/dist/index.d.ts:3:8`, not on my files.** And I can't change project config such as esModuleInterop to make it work (btw I'd break tons of *other* stuff).

Since `@types/express` use `export = e` (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express)), it _cant_ be imported the same as express rate limit. So [this line](https://github.com/nfriedly/express-rate-limit/blob/master/source/types.ts#L4) should be changed imho. Also, the types should be defined in the DefinitelyTyped repo, not on this repo.

Let me know if you agree.

**Comment by gamemaker1** [comment]
Are you importing express anywhere in your project? If yes, you should not be able to import it using `import ... from ... ` without `esModuleInterop` set to `true`.

Even so, there are two possible solutions:

- Use `const rateLimit = require('express-rate-limit')` to import the library instead of `import rateLimit from 'express-rate-limit'`
- Set `skipLibChecks` to `true` in your `tsconfig.json` to supress the error.

> Also, the types should be defined in the DefinitelyTyped repo (actually there is already the project), not on this repo

DefinitelyTyped is for libraries that are written in Javascript, or more generally, libraries that do not bundle type definitions. Since this project is written in Typescript, it makes it easier to bundle the type definitions along with the library than take the pains to maintain a `@types` package and update it every time we make the smallest change in the type definitions.

**Comment by gamemaker1** [comment]
> So this line should be changed imho

Hmmm... let's give it a try - could you please try the following:

```
npm install https://raw.githubusercontent.com/gamemaker1/test/express-rate-limit-hotfix/assets/express-rate-limit-6.0.3.tgz
```

**Comment by DavideViolante** [comment]
Yes, const rateLimit = require would work, but there is something wrong here since no other lib I'm using in the project need to be imported as that.

I think both the examples `ts-cjs` and `ts-esm` of this repo are wrong since they are **not working with TS default options**, so with `esModuleInterop` to false and `skipLibChecks` to false.

Yes, it does work indeed with the hotfix, I think it should be the default behaviour.

**Comment by gamemaker1** [comment]
Hmmm the 'hotfix' uses named imports for express types (`import {Request, Response} from 'express` and instead of `import Express from 'express` and then `Express.Request, Express.Response`), no harm in making that change permanent.

@nfriedly should I open a PR with this change?

**Comment by gamemaker1** [comment]
> they are not working with TS default options, so with esModuleInterop to false and skipLibChecks to false.

That's true - maybe we should take a look at the options in the tsconfigs for the tests and keep them to a minimum.

**Comment by gamemaker1** [comment]
Fixed in 6.0.5 🎉

**Comment by gamemaker1** [comment]
Thanks for your help @DavideViolante

**Comment by nfriedly** [comment]
Yes! Thank you both!
